### ISSUE TITLE
TypeError: Cannot read property 'getBoundingClientRect' 

### ISSUE THREAD

**Issue by dimarconicola** [metonym/svelte-accessible-accordion#3]
TypeError: Cannot read property 'getBoundingClientRect' of null
    at HTMLButtonElement.click_handler_1

**Comment by dimarconicola** [comment]
Can you guys help?

**Comment by metonym** [comment]
Can you provide a reproduction of the error in the [Svelte REPL](https://svelte.dev/repl/85be3a105c3f4fe0892150380914be96?version=3.30.0)?

**Comment by metonym** [comment]
#5 should fix this by performing a null check on the accordion item reference.

Published to NPM in [version 1.0.1](https://github.com/metonym/svelte-accessible-accordion/releases/tag/v1.0.1)
