### ISSUE TITLE
Cannot use it within the `<form>`

### ISSUE THREAD

**Issue by smiile8888** [metonym/svelte-accessible-accordion#6]
Problem:
I wanted to use it in the `<form>` but the accordion using the `<button>` and it becomes `type="submit"` automatically when using with `<form>`

Expected:
Can use as a normal accordion even it's used in the `<form>`, maybe `type="button"` could be added to the `AccordionItem` component

I'm not sure is there a way or any prop I can pass to prevent it?
Thank you!

**Comment by metonym** [comment]
@smiile8888 Thank you for raising this issue. `type="button"` has been added to the AccordionItem button to prevent the default behavior when using the component inside a `form` element.

Published to npm in [version 1.0.2](https://github.com/metonym/svelte-accessible-accordion/releases/tag/v1.0.2)

**Comment by smiile8888** [comment]
@metonym Thank you very much for addressing the issue 😄
